using System;

namespace Prj1Day1Con
{
   class Program
    {
        static void Main()
        {
            int x = 10;
            int d = 2;

            try
            {
                Console.WriteLine("Enter a number: numerator : ");
                x = Convert.ToInt32(Console.ReadLine());
                Console.WriteLine("Enter another number: denominator : ");
                d = Convert.ToInt32(Console.ReadLine());
                Console.WriteLine("The square of the number enetered is : " + (x * x));
                int y = x / d;
                Console.WriteLine("Div Result: " + y);
            }
            catch(FormatException e)
            {
                Console.WriteLine("This is a " + e.Message + " exception!");
            }
            catch(DivideByZeroException e)
            {
                Console.WriteLine("This is a " + e.Message + " exception!");
            }
            Console.WriteLine("The Program continues..");

        }

    }
}












using System;

namespace Prj1Day1Con
{
   class Program
    {
        static void Main()
        {
            Console.WriteLine("Enter a number: numerator : ");
            int x = Convert.ToInt32 (Console.ReadLine());
            Console.WriteLine("Enter another number: denominator : ");
            int d = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("The square of the number enetered is : " + (x*x));
            try
            {
                int y = x / d;
                Console.WriteLine("Div Result: " + y);
            }
            catch(DivideByZeroException e)
            {
                Console.WriteLine("This is a " + e.Message + " exception!");
            }
            Console.WriteLine("The Program continues..");

        }

    }
}


